#!/usr/bin/node

// Libraries
var contains = require("multiple-contains") // Contains library
var path = require('path')                  // Path utils library
var EasyWizard = require('easywizard')      // Easy Wizard library

// Loading Configuration
var cm = require('jsonfile-config-manager')
var configPath = path.resolve(__dirname, '../config/')
cm.addFile(path.join(configPath, 'users.json'), null, false)
cm.addFile(path.join(configPath, 'bot.json'), null, false)
cm.addFile(path.join(configPath, 'literals.json'), null, false)

// Variables
var users    = cm.config.users
var language = cm.config.bot.defaultLanguage
var literal  = cm.config.literals[language]
var wizard   = path.join(configPath, 'adduser.' + language + ".wizard")
var ew       = new EasyWizard()
var response
var timeout


// Checking step
ew.emitter.once('paused', function() {

  // Getting response object
	response = ew.getObject()

  // Checking if friend username is empty
  if (!response.friendname) {
    console.log(literal.emptyUsernameError)
    ew.setNextStep("1")
		ew.emitter.emit('continue')
		return
	}

  // Checking if user was included in array previously
  if (contains(users, response.friendname, 'exists')) {
    console.log(literal.userAuthorizedError)
		ew.emitter.emit('continue')
		return
	}

  // Adding new user and updating file
  users.push(response.friendname)
  cm.updateBranchFile('users')
  console.log(literal.addUserSuccessMessage)
  ew.emitter.emit('continue')

})

// Checking final step
ew.emitter.once('end', function() {
	clearTimeout(timeout)
	process.exit(0)
})


console.log(literal.addUserWellcomeMessage + '.')
timeout = setTimeout(function(){ ew.run(wizard) }, 200)
